# Generated by Django 5.0.3 on 2024-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('cnpj', models.CharField(blank=True, default='--/--', max_length=18)),
                ('tipo_contrato', models.CharField(choices=[('Estágio', 'Estágio'), ('CLT', 'CLT'), ('PJ', 'PJ')], max_length=10)),
                ('tempo_contrato', models.CharField(choices=[('6 Meses', '6 Meses'), ('1 Ano', '1 Ano'), ('2 Anos', '2 Anos'), ('Indeterminado', 'Indeterminado')], max_length=15)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vr_ativo', models.BooleanField(default=False)),
                ('vr_valor_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vt_ativo', models.BooleanField(default=False)),
                ('vt_valor_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('setor', models.CharField(choices=[('Lojas', 'Lojas'), ('SIAPE', 'SIAPE'), ('INSS', 'INSS'), ('TI', 'TI'), ('Marketing', 'Marketing'), ('Operacional', 'Operacional'), ('Outros', 'Outros')], max_length=20)),
                ('status_atividade', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=7)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
