# Generated by Django 5.0.3 on 2024-04-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='horario_diario',
            field=models.CharField(choices=[('6 Horas', '6 Horas'), ('9 Horas', '9 Horas')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='turno',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Integral', 'Integral')], max_length=10, null=True),
        ),
    ]
