# Generated by Django 5.0.3 on 2024-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_funcionario_horario_diario_funcionario_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='empresas',
            field=models.CharField(choices=[('BOREAL', 'BOREAL'), ('MONEY', 'MONEY'), ('PARK GUAIBA', 'PARK GUAIBA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(choices=[('Atendimento POA', 'Atendimento POA'), ('Atendimento SM', 'Atendimento SM'), ('Atendimento SLE', 'Atendimento SLE'), ('SIAPE', 'SIAPE'), ('INSS', 'INSS'), ('TI', 'TI'), ('Marketing', 'Marketing'), ('Operacional', 'Operacional'), ('Outros', 'Outros')], max_length=20),
        ),
    ]
