# Generated by Django 5.0.3 on 2024-04-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumbEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('senha_email', models.CharField(blank=True, max_length=100, null=True)),
                ('operadora_site', models.CharField(blank=True, default='desconhecido', max_length=11, null=True)),
                ('ddd', models.CharField(blank=True, default='00', max_length=2, null=True)),
                ('numero', models.CharField(blank=True, max_length=9, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
