# Generated by Django 5.0.3 on 2024-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbemail',
            name='status',
            field=models.CharField(blank=True, default='ativo', max_length=12, null=True),
        ),
    ]
