# Generated by Django 5.0.3 on 2024-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0002_numbemail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numbemail',
            old_name='status',
            new_name='status_numb',
        ),
        migrations.AddField(
            model_name='numbemail',
            name='status_email',
            field=models.CharField(blank=True, default='ativo', max_length=12, null=True),
        ),
    ]
